apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gaurikapoplai21/Kubecon-europe.git
    targetRevision: main
    path: apps/demo-service/overlays/good
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true