apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-owner-label
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-owner-label
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - demo
      validate:
        message: "Deployments in demo namespace must have an owner label."
        pattern:
          spec:
            template:
              metadata:
                labels:
                  owner: "?*"